spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/financemanager
    username: root
    password: admin

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true

  jwt:
    private.key: classpath:app.key
    public.key: classpath:app.pub

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: personalfinancemanagerapp1@gmail.com
    password: hzogofazrtioykzt

  sms:
    enabled: true
    account-sid: ACbe082606ed3b023b0c61309292ee513f
    auth-token: bb6fc24a5c300f28ce22d58ca68caa26
    number: +13465177132

  app:
    notification-days-default: 7
    sms-days-default: 3